### ISSUE TITLE
List or Seq validation in Forms

### ISSUE THREAD

**Issue by KarelCemus** [aselab/scala-activerecord#68]
I use this framework with Play 2 and I encountered the following use-case. I have a User entity with lists of his emails and his phone numbers. The model looks like this:

```scala
case class User(  @Email emails: List[String], phones: List[Int] )
```

Now I want to use this model in forms to let users fill the model in. There are two issues.

1. The form object doesn't validate these emails. 
2. When the phone number is not Int, i.e., conversion fails, it registers the error to "phones" field 
instead of, e.g., "phones[2]". Consequently, I am unable to match the error to the proper instance.

Is there any workaround for this?

**Comment by y-yoshinoya** [comment]
Thank you for your feedback.

>  The form object doesn't validate these emails. 

Email annotation is only works for `String` field.
If you can use `List[String]` field, override `doValidate` in Model.

> When the phone number is not Int, i.e., conversion fails, it registers the error to "phones" field 
> instead of, e.g., "phones[2]". Consequently, I am unable to match the error to the proper instance.

Sorry, the form validation for List or Seq of any type is not supported, because it is not possible to save the List type (not `Array[Byte]`) directly into the database.
But, convenient likely it looks in `ActiveModel`. We might future to implement it. (or your pull-request :+1:  )

As a workaround, you can use form validation for nested `ActiveModel` or `ActiveRecord` model.

```scala
case class User(emails: List[Email]) extends ActiveModel
case class Email(@Email email: String) extends ActiveModel
...

object Main extends App {
  val emails = List(Email("invalidAddress"))
  val user = User(emails)
  user.validate  // => returns false
  user.formErrors.map(e => s"${e.key} is ${e.error}").toList
  // => returns List(emails[0][email] is activerecord.errors.invalid)
}
```

And, sample code is the following:
https://github.com/y-yoshinoya/scala-activerecord-issue68

Thank you.

**Comment by KarelCemus** [comment]
Thank you for your response. I noticed the framework is tightly bound to the database and its use without  it is difficult and limited. I'll use the workaround, its sufficient for now. Thanks.
